stages:
  data_ingestion:
   cmd: python src/pipeline/stage_01_ingestion.py
   deps: 
   - src/components/data_ingestion.py
   - data/raw
   params:
    - configs/components_params.yaml:
       - data_ingestion
   outs:
     - artifacts/ingestion_artifact/data_ingestion.json
  data_validation:
    cmd: python src/pipeline/stage_02_validation.py
    deps:
      - src/components/data_validation.py
      - artifacts/ingestion_artifact/data_ingestion.json
      - configs/schema.yaml
    outs:
    - artifacts/validation_artifact/data_validation.json
  data_profiling:
   cmd: python src/pipeline/stage_03_profiling.py
   deps:
    - src/components/data_profiling.py
    - artifacts/validation_artifact/data_validation.json
    - src/profilers/validation_profiler.py
   outs:
    - artifacts/profiling_artifacts/data_profiling_dist.json
    - artifacts/profiling_artifacts/data_profiling_missing_val.json
    - artifacts/profiling_artifacts/data_profiling_stats.json
    - artifacts/profiling_artifacts/data_profiling_summary.json
    - artifacts/profiling_artifacts/data_profiling.json
  feature_engineer:
   cmd: python src/pipeline/stage_04_feature_engineer.py
   deps:
     - src/features/make_features.py
     - artifacts/validation_artifact/data_validation.json
   outs:
      - artifacts/feature_engineer_artifact/feature_engineer.json
  data_transformation:
    cmd: python src/pipeline/stage_05_data_transformation.py
    deps:
      - src/components/data_transformation.py
      - artifacts/feature_engineer_artifact/feature_engineer.json
      - configs/transformation_schema.yaml
    outs:
      - artifacts/transformation_artifact/data_transformation.json
      - artifacts/transformation_artifact/preprocessor.joblib
      - data/processed/x_train.parquet
      - data/processed/x_test.parquet
      - data/processed/y_train.parquet
      - data/processed/y_test.parquet
  model_experiment:
    cmd: python src/pipeline/stage_06_experiment.py
    deps:
      - src/pipeline/stage_06_experiment.py
      - src/experiment/runner.py
      - src/experiment/model_factory.py
      - src/experiment/model_registry.py
      - src/tracking/mlflow_tracker.py
      - artifacts/transformation_artifact/data_transformation.json
      - configs/experiment_params.yaml
    outs:
      - artifacts/experiment_artifact/experiment.json
  model_tuning:
    cmd: python src/pipeline/stage_08_model_tuning.py
    deps:
      - src/pipeline/stage_08_model_tuning.py
      - src/components/model_tuner.py
      - src/experiment/model_factory.py
      - src/experiment/model_registry.py
      - src/tracking/mlflow_tracker.py
      - artifacts/transformation_artifact/data_transformation.json
      - artifacts/transformation_artifact/preprocessor.joblib
      - artifacts/experiment_artifact/experiment.json
      - configs/experiment_params.yaml
    outs:
      - artifacts/model_tuning_artifact/model_tuning.json
      - models/burnout_classifier.joblib
  model_registry:
    cmd: python src/pipeline/stage_09_model_registry.py
    deps:
      - src/pipeline/stage_09_model_registry.py
      - src/components/model_registry.py
      - src/tracking/mlflow_tracker.py
      - src/entity/configs/model_registry_cfg.py
      - src/entity/artifacts/model_registry_artifact.py
      - artifacts/feature_engineer_artifact/feature_engineer.json
      - artifacts/model_tuning_artifact/model_tuning.json
      - artifacts/transformation_artifact/data_transformation.json
      - models/burnout_classifier.joblib
      - configs/experiment_params.yaml
      - configs/registry_params.yaml
      - configs/schema.yaml
    outs:
      - artifacts/model_registry_artifact/model_registry.json
