stages:
  data_ingestion:
   cmd: python src/pipeline/stage_01_ingestion.py
   deps: 
   - src/components/data_ingestion.py
   - data/raw
   params:
    - configs/components_params.yaml:
       - data_ingestion
   outs:
     - artifacts/ingestion_artifact/data_ingestion.json
  data_validation:
    cmd: python src/pipeline/stage_02_validation.py
    deps:
      - src/components/data_validation.py
      - artifacts/ingestion_artifact/data_ingestion.json
      - configs/schema.yaml
    outs:
    - artifacts/validation_artifact/data_validation.json
  data_profiling:
   cmd: python src/pipeline/stage_03_profiling.py
   deps:
    - src/components/data_profiling.py
    - artifacts/validation_artifact/data_validation.json
    - src/profilers/validation_profiler.py
   outs:
    - artifacts/profiling_artifacts/data_profiling_dist.json
    - artifacts/profiling_artifacts/data_profiling_missing_val.json
    - artifacts/profiling_artifacts/data_profiling_stats.json
    - artifacts/profiling_artifacts/data_profiling_summary.json
    - artifacts/profiling_artifacts/data_profiling.json
  feature_engineer:
   cmd: python src/pipeline/stage_04_feature_engineer.py
   deps:
     - src/features/make_features.py
     - artifacts/validation_artifact/data_validation.json
   outs:
      - artifacts/feature_engineer_artifact/feature_engineer.json
  data_transformation:
    cmd: python src/pipeline/stage_05_data_transformation.py
    deps:
      - src/components/data_transformation.py
      - artifacts/feature_engineer_artifact/feature_engineer.json
      - configs/transformation_schema.yaml
    outs:
      - artifacts/transformation_artifact/data_transformation.json
      - artifacts/transformation_artifact/preprocessor.joblib
      - data/processed/x_train.parquet
      - data/processed/x_test.parquet
      - data/processed/y_train.parquet
      - data/processed/y_test.parquet
  model_training:
    cmd: python src/pipeline/stage_06_model_training.py
    deps:
      - src/pipeline/stage_06_model_training.py
      - artifacts/transformation_artifact/data_transformation.json
      - artifacts/transformation_artifact/preprocessor.joblib
      - configs/experiment_params.yaml
    outs:
      - artifacts/model_artifact/model_training.json
      - models/burnout_classifier.joblib
