from src.constants import (
    ARTIFACT_DIR,
    INGESTION_ARTIFACT_DIR,
    INGESTION_ARTIFACT,
    VALIDATION_ARTIFACT,
    VALIDATION_ARTIFACT_DIR,
    PROFILING_ARTIFACT_DIR,
    PROFILING_DISTRIBUTION_ARTIFACT,
    PROFILING_MISSING_VALUES_ARTIFACT,
    PROFILING_STATS_ARTIFACT,
    PROFILING_SUMMARY_ARTIFACT,
)

from .base_paths import PROJECT_ROOT

ARTIFACT_DIR_PATH = PROJECT_ROOT / ARTIFACT_DIR

INGESTION_ARTIFACT_DIR_PATH = (
    ARTIFACT_DIR_PATH / INGESTION_ARTIFACT_DIR / INGESTION_ARTIFACT
)

VALIDATION_ARTIFACT_DIR_PATH = (
    ARTIFACT_DIR_PATH / VALIDATION_ARTIFACT_DIR / VALIDATION_ARTIFACT
)

PROFILING_ARTIFACT_SUMM_DIR_PATH = (
    ARTIFACT_DIR_PATH / PROFILING_ARTIFACT_DIR / PROFILING_SUMMARY_ARTIFACT
)

PROFILING_ARTIFACT_DIST_DIR_PATH = (
    ARTIFACT_DIR_PATH / PROFILING_ARTIFACT_DIR / PROFILING_DISTRIBUTION_ARTIFACT
)

PROFILING_ARTIFACT_MISSING_VALUES_DIR_PATH = (
    ARTIFACT_DIR_PATH / PROFILING_ARTIFACT_DIR / PROFILING_MISSING_VALUES_ARTIFACT
)

PROFILING_ARTIFACT_STATS_DIR_PATH = (
    ARTIFACT_DIR_PATH / PROFILING_ARTIFACT_DIR / PROFILING_STATS_ARTIFACT
)
PROFILING_ARTIFACT_DIR_PATH = (
    ARTIFACT_DIR_PATH / PROFILING_ARTIFACT_DIR / "data_profiling.json"
)

FEATURE_ENGINEER_ARTIFACT_DIR_PATH = (
    ARTIFACT_DIR_PATH / "feature_engineer_artifact" / "feature_engineer.json"
)
