from src.constants import (
    COMPONENT_YAML,
    EXPERIMENT_YAML,
    SCHEMA_YAML,
    TRANSFORMATION_YAML,
    YAML_DIR_NAME,
)

from .base_paths import PROJECT_ROOT

YAML_DIR_PATH = PROJECT_ROOT / YAML_DIR_NAME

SCHEMA_YAML_DIR_PATH = YAML_DIR_PATH / SCHEMA_YAML
COMPONENT_YAML_DIR_PATH = YAML_DIR_PATH / COMPONENT_YAML
TRANSFORMATION_YAML_DIR_PATH = YAML_DIR_PATH / TRANSFORMATION_YAML
EXPERIMENT_YAML_DIR_PATH = YAML_DIR_PATH / EXPERIMENT_YAML
