from src.constants import (
    DATA_DIR,
    RAW_DATA_DIR,
    INTERIM_DATA_DIR,
    PROCESSED_DATA_DIR,
    RAW_DATA_NAME,
)

from .base_paths import PROJECT_ROOT

DATA_DIR_PATH = PROJECT_ROOT / DATA_DIR

RAW_DATA_DIR_PATH = DATA_DIR_PATH / RAW_DATA_DIR

INTERIM_DATA_DIR_PATH = DATA_DIR_PATH / INTERIM_DATA_DIR

PROCESSED_DATA_DIR_PATH = DATA_DIR_PATH / PROCESSED_DATA_DIR

RAW_DATA_PATH = RAW_DATA_DIR_PATH / RAW_DATA_NAME
