from src.constants import (
    DATA_DIR,
    RAW_DATA_DIR,
    INTERIM_DATA_DIR,
    PROCESSED_DATA_DIR,
    RAW_DATA_NAME,
    X_TRAIN_NAME,
    X_TEST_NAME,
    Y_TEST_NAME,
    Y_TRAIN_NAME,
)

from .base_paths import PROJECT_ROOT

DATA_DIR_PATH = PROJECT_ROOT / DATA_DIR

RAW_DATA_DIR_PATH = DATA_DIR_PATH / RAW_DATA_DIR

INTERIM_DATA_DIR_PATH = DATA_DIR_PATH / INTERIM_DATA_DIR

PROCESSED_DATA_DIR_PATH = DATA_DIR_PATH / PROCESSED_DATA_DIR

RAW_DATA_PATH = RAW_DATA_DIR_PATH / RAW_DATA_NAME

X_TRAIN_PATH = PROCESSED_DATA_DIR_PATH / X_TRAIN_NAME
X_TEST_PATH = PROCESSED_DATA_DIR_PATH / X_TEST_NAME
Y_TRAIN_PATH = PROCESSED_DATA_DIR_PATH / Y_TRAIN_NAME
Y_TEST_PATH = PROCESSED_DATA_DIR_PATH / Y_TEST_NAME
