from src.constants import (
    DATA_DIR,
    RAW_DATA_DIR,
    PROJ_ROOT,
    INTERIM_DATA_DIR,
    PROCESSED_DATA_DIR,
    RAW_DATA_NAME,
    INGESTION_ARTIFACT_DIR,
    ARTIFACT_DIR,
    LOG_DIR,
    YAML_DIR_NAME,
    SCHEMA_YAML,
    INGESTION_ARTIFACT,
)

DATA_DIR_PATH = PROJ_ROOT / DATA_DIR
RAW_DATA_DIR_PATH = DATA_DIR_PATH / RAW_DATA_DIR
INTERIM_DATA_DIR_PATH = DATA_DIR_PATH / INTERIM_DATA_DIR
PROCESSED_DATA_DIR_PATH = DATA_DIR_PATH / PROCESSED_DATA_DIR
RAW_DATA_PATH = RAW_DATA_DIR_PATH / RAW_DATA_NAME

# Artifact Config
ARTIFACT_DIR_PATH = PROJ_ROOT / ARTIFACT_DIR
INGESTION_ARTIFACT_DIR_PATH = (
    ARTIFACT_DIR_PATH / INGESTION_ARTIFACT_DIR / INGESTION_ARTIFACT
)

# log dir
LOG_DIR_PATH = PROJ_ROOT / LOG_DIR

# Schema (Validation)

YAML_DIR_PATH = PROJ_ROOT / YAML_DIR_NAME
SCHEMA_YAML_DIR_PATH = YAML_DIR_PATH / SCHEMA_YAML
