target_column: Burnout_Risk_Level

columns:

  Major_Category:
    type: categorical

  Year_of_Study:
    type: categorical

  Pre_Semester_GPA:
    type: numerical

  Weekly_GenAI_Hours:
    type: numerical

  Primary_Use_Case:
    type: categorical

  Prompt_Engineering_Skill:
    type: categorical

  Tool_Diversity:
    type: numerical

  Paid_Subscription:
    type: boolean

  Traditional_Study_Hours:
    type: numerical

  Perceived_AI_Dependency:
    type: numerical

  Institutional_Policy:
    type: categorical

  Anxiety_Level_During_Exams:
    type: numerical

  Post_Semester_GPA:
    type: numerical

  Skill_Retention_Score:
    type: numerical

  Burnout_Risk_Level:
    type: categorical